### ISSUE TITLE
The `sources` field in the sourcemap seems invalid

### ISSUE THREAD

**Issue by darrachequesne** [niklasvh/base64-arraybuffer#32]
Hi! It seems the `sources` field in the sourcemap `base64-arraybuffer.es5.js.map` is invalid:

```
{"version":3,"file":"base64-arraybuffer.es5.js","sources":["../../src/index.ts"],"sourcesContent":[null],"names":[], ...
```

It should be `../src/index.ts` I think.

```
node_modules/
└── base64-arraybuffer
    ├── dist
    │   ├── base64-arraybuffer.es5.js
    │   ├── base64-arraybuffer.es5.js.map
    │ ...
    ├── package.json
    ├── README.md
    └── rollup.config.ts
```

Not sure why though.

Related: https://github.com/socketio/socket.io-client/issues/1520

**Comment by kaaax0815** [comment]
+1 This is extremely important

**Comment by darrachequesne** [comment]
It seems to be a known issue: https://github.com/rollup/rollup/issues/4248

As a workaround, you can use the `sourcemapPathTransform` option in `rollup.config.js`:

```js
export default {
    input: `src/index.ts`,
    output: [
        {
            file: pkg.main,
            name: pkg.name,
            format: 'umd',
            banner,
            sourcemap: true,
            sourcemapPathTransform: (sourcePath) => {
                return sourcePath.substring('../'.length);
            },
        },
    [...]
}
```

This produces `"sources":["../src/index.ts"]` instead of `"sources":["../../src/index.ts"]`.

**Comment by darrachequesne** [comment]
If anyone is interested, we went ahead and forked the project: https://github.com/socketio/base64-arraybuffer

It is published as `@socket.io/base64-arraybuffer@1.0.2`, included in `engine.io-parser@5.0.3` (and thus in latest `socket.io-client`, as it is a transitive dependency).

There are two additional commits:

- https://github.com/socketio/base64-arraybuffer/commit/d30e7cc877d6fd68555856b611e3f22940b00f4d
- https://github.com/socketio/base64-arraybuffer/commit/1584b784e7cf242d7abad977e280d9ac5bb5e299

We will revert back to the original package once the changes are merged here. Thanks!

**Comment by niklasvh** [comment]
Sorry for the delay. This has been fixed in 1.0.2

**Comment by darrachequesne** [comment]
It seems there is still an issue with the sourcemap file in version `1.0.2`. There is no warning anymore (yay :tada:), but it seems the sourcemap isn't properly loaded.

With `base64-arraybuffer@1.0.2`:

![Screenshot from 2022-01-23 07-39-11](https://user-images.githubusercontent.com/13031701/150667694-06115e50-2862-4030-be19-e23d7ce13566.png)

With `@socket.io/base64-arraybuffer@1.0.2`:

![Screenshot from 2022-01-23 07-41-45](https://user-images.githubusercontent.com/13031701/150667727-65b28e11-f089-4b0e-b495-11fd2b159c66.png)

It seems the `sourcesContent` field is ignored in the sourcemap:

```
{"version":3,"file":"base64-arraybuffer.es5.js","sources":["../../src/index.ts"],"sourcesContent":["const chars = 'ABCDEFGHIJKLMNOPQR...
```

Though that may be a bug from the [`source-map-loader`](https://github.com/webpack-contrib/source-map-loader) plugin.
